apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: chatbot-rd-oct7-rm2-1
  janus-idp.io/tekton: chatbot-rd-oct7-rm2-1
  backstage.io/kubernetes-id: chatbot-rd-oct7-rm2-1
  backstage.io/kubernetes-namespace: chatbot-rd-oct7-rm2-1
  app.kubernetes.io/part-of: chatbot-rd-oct7-rm2-1
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
